name: quack
version: git
summary: Duck DNS client
description: |
  Keep your IP address updated on Duck DNS
grade: stable

architectures:
  - build-on: amd64
    run-on: [amd64, i386, armhf, arm64, ppc64el]

confinement: strict
base: core20

parts:
  quack:
    plugin: go
    source: .
    source-type: git
    
apps:
  config:
    environment: 
      QUACK_CONFIG_DIR: "$SNAP_DATA"
    command: bin/quack config
  
  set:
    environment: 
      QUACK_CONFIG_DIR: "$SNAP_DATA"
    command: bin/quack set
  
  quack:
    environment: 
      QUACK_CONFIG_DIR: "$SNAP_DATA"
    command: bin/quack
    daemon: simple
    plugs:
      - network
    